export const Fonts = {
    black: "black",
    blackItalic: "blackItalic",
    extraBold: "extraBold",
    extraBoldItalic: "extraBoldItalic",
    bold: "bold",
    boldItalic: "boldItalic",
    semiBold: "semiBold",
    semiBoldItalic: "semiBoldItalic",
    medium: "medium",
    mediumItalic: "mediumItalic",
    regular: "regular",
    italic: "italic",
    light: "light",
    lightItalic: "lightItalic",
    extraLight: "extraLight",
    extraLightItalic: "extraLightItalic",
    thin: "thin",
    thinItalic: "thinItalic",
}